import = ["~/.config/alacritty/themes/themes/nord.toml"]
live_config_reload = true

[cursor]
blink_interval = 500

[cursor.style]
blinking = "Always"

[env]
TERM = "xterm-256color"

[font]
# size = 14.5
size = 16

[font.normal]
# family = "MesloLGSDZ Nerd Font"
# family = "BlexMono Nerd Font Mono"
# family = "CodeNewRoman Nerd Font"
# family = "Cousine Nerd Font"
family = "FiraCode Nerd Font"
style = "Regular"

[window]
decorations = "buttonless"
opacity = 0.99
startup_mode = "Windowed"
